version: '3'
services:
  anime_notification_bot_api:
    container_name: anime_notification_bot_api
    build:
      context: /
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__PostgreSql: "Server=db;Port=5432;Database=anime_notification_bot;User Id=sa;Password=P@ssw0rd"
 
  anime_notification_bot_quartz:
    container_name: anime_notification_bot_quartz
    build:
      context: /
      dockerfile: docker/quartz/Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__PostgreSql: "Server=db;Port=5432;Database=anime_notification_bot;User Id=sa;Password=P@ssw0rd"
 
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=anime_notification_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}