version: '3.9'
services:

  anime_notification_bot_api:
    image: kamaksimka/anime-notification-bot-api:latest
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__PostgreSql: "Server=db;Port=5432;Database=anime_notification_bot;User Id=sa;Password=P@ssw0rd"
      BotConfiguration__BotToken: ""
      BotConfiguration__HostAddress: "https://kamaksimka.ru"
      QuartzConfig__NotifyAboutAnimeJobCronSchedule: "30 * * ? * * *"
    restart: always
    networks:
      - net

  anime_notification_bot_quartz:
    container_name: anime_notification_bot_quartz
    image: kamaksimka/anime-notification-bot-quartz:latest
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__PostgreSql: "Server=db;Port=5432;Database=anime_notification_bot;User Id=sa;Password=P@ssw0rd"
      QuartzConfig__AnimeNotificationCronSchedule: "0 * * ? * * *"
      QuartzConfig__UpdateAnimesCronSchedule: "0 0 12 ? * * *"
      QuartzConfig__UpdateAnimeCommentsCronSchedule: "0 0 0 ? * 1/7 *"
    restart: always
    networks:
      - net
 
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=anime_notification_bot
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
    restart: always

  webserver:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - net
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  pgdata: {}